version: 0.2
phases:
  install:
    commands:
      - npm install time
      - aws cloudformation package --template-file template.yml
                                   --s3-bucket foreignforce-codebuild-artifacts
                                   --output-template-file outputTemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputTemplate.yml
