Resources:
  TimeFunction:
    Type: "AWS::Lambda::Function"
    Properties: 
      Code: ./
      Description: Description
      FunctionName: TimeFunction
      Handler: index.handler
      Role: arn:aws:iam::921647845311:role/lambda_basic_execution
      Runtime: nodejs8.10

  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: foreignforce-appsync-dynamodb-role
      ManagedPolicyArns:
        - Ref: AppSyncDynamoDBPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
    DependsOn:
      - AppSyncDynamoDBPolicy

  AppSyncDynamoDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy to allow AWS AppSync to access the tables created by this template.
      Path: /appsync/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource: !Join [ "", [ "arn:aws:dynamodb:eu-central-1:921647845311:table/foreignforce-mobilehub-1673183565-setting", "*" ] ]
