Resources:
  TimeFunction:
    Type: "AWS::Lambda::Function"
    Properties: 
      Code: ./
      Description: Description
      FunctionName: TimeFunction
      Handler: index.handler
      Role: arn:aws:iam::921647845311:role/lambda_basic_execution
      Runtime: nodejs8.10

  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: foreignforce-appsync-dynamodb-role
      ManagedPolicyArns:
        - Ref: AppSyncDynamoDBPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - appsync.amazonaws.com
    DependsOn:
      - AppSyncDynamoDBPolicy

  AppSyncDynamoDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Managed policy to allow AWS AppSync to access the tables created by this template.
      Path: /appsync/
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource: !Join [ "", [ "arn:aws:dynamodb:eu-central-1:921647845311:table/foreignforce-mobilehub-1673183565-setting", "*" ] ]

  UserPool:
    Type: "AWS::Cognito::UserPool"
    Description: "A Cognito user pool for authenticating users"
    Properties:
      UserPoolName: foreignforce-user-pool

  UserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Description: "App Client used by AWS AppSync"
    Properties:
      ClientName: foreignforce-appsync-client
      UserPoolId: !Ref UserPool

  DynamoDBUserTable:
    Type: "AWS::DynamoDB::Table"
    Description: "Data store for AWS AppSync"
    Properties:
      TableName: foreignforce-user-table
      AttributeDefinitions:
        - AttributeName: "NoteId"
          AttributeType: "S"
        - AttributeName: "UserId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "NoteId"
          KeyType: "HASH"
        - AttributeName: "UserId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  AppSyncApi:
    Type: "AWS::AppSync::GraphQLApi"
    Description: "The GraphQL API"
    Properties:
      AuthenticationType: "AMAZON_COGNITO_USER_POOLS"
      Name: foreignforce
      UserPoolConfig:
        UserPoolId: !Ref UserPoolClient
        AwsRegion: !Sub ${AWS::Region}
        DefaultAction: "ALLOW"

  AppSyncSchema:
    Type: "AWS::AppSync::GraphQLSchema"
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      DefinitionS3Location: ./schema.graphql
